/*
 * Project generated by Templater
 * Argore 2024
 */

#include <stdio.h>
#include <iostream>
#include "Client/cClient.h"

int main()
{
	
	cClient client;

	client.create( 8000 );
	
	uAddressCode external_code = client.getExternalIP();
	printf( "local code: %i\n", external_code.c );

	uAddressCode asd;
	printf( "a: %i\n", asd.c );

	std::string code;
	printf( "Code: " );
	std::cin >> code;

	uAddressCode code_union;	
	code_union.c = std::stoi( code );

	// client.connect( "192.165.30.70", 8000 ); /
	// / linux address
	// client.connect( "193.234.137.55", 8000 ); // argore address

	client.connect( code_union.dump().c_str(), 8000);

	while ( 1 )
	{
		Sleep( 100 );
	}

	return 0;
}

